"""Writers for expected.jsonl, MANIFEST.md and _generator_meta.json
(DATA_SPEC.md §8-9).
"""

from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path

from .models import Document


def _nfc(p: str) -> str:
    return unicodedata.normalize("NFC", p)


def write_expected_jsonl(documents: list[Document], path: Path) -> None:
    rows = []
    for doc in documents:
        row = doc.expected_row()
        row["files"] = sorted(_nfc(f) for f in row["files"])
        rows.append(row)
    rows.sort(key=lambda r: r["files"][0] if r["files"] else "")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False, sort_keys=True))
            f.write("\n")


def write_generator_meta(
    documents: list[Document],
    buyer_identities: list[dict],
    path: Path,
) -> None:
    meta = {
        "buyer_identities": buyer_identities,
        "documents": [
            {
                "doc_id": d.doc_id,
                "doc_type": d.doc_type.value if d.doc_type else None,
                "tags": d.tags,
                "files": sorted(_nfc(f) for f in d.files),
            }
            for d in documents
        ],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(meta, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_manifest(
    documents: list[Document],
    corrupt_files: dict[str, str],
    path: Path,
    *,
    input_files: int,
    duplicate_files: int,
    unique_documents: int,
    decisions: list[str],
) -> None:
    lines = [
        "# MANIFEST — synthetic corpus coverage",
        "",
        "Generated by `scripts/generate_data.py`. Do not hand-edit.",
        "",
        "## Ground-truth decisions made by the generator",
        "",
        "These are the implementer's calls on points DATA_SPEC.md leaves open:",
        "",
    ]
    for d in decisions:
        lines.append(f"- {d}")
    lines += ["", "## Coverage table", "", "| path | doc_type | format | tags |", "|---|---|---|---|"]

    rows: list[tuple[str, str, str, str]] = []
    for doc in documents:
        doc_type = doc.doc_type.value if doc.doc_type else "null"
        tags = ", ".join(doc.tags)
        for f in sorted(_nfc(x) for x in doc.files):
            fmt = f.rsplit(".", 1)[-1]
            rows.append((f, doc_type, fmt, tags))
    for name, path_rel in sorted(corrupt_files.items()):
        rows.append((path_rel, "null", path_rel.rsplit(".", 1)[-1], f"corrupt:{name}"))

    rows.sort(key=lambda r: r[0])
    for path_rel, doc_type, fmt, tags in rows:
        lines.append(f"| {path_rel} | {doc_type} | {fmt} | {tags} |")

    lines += [
        "",
        "## Report balance",
        "",
        "```",
        f"input_files      = {input_files}",
        f"duplicate_files  = {duplicate_files}",
        f"unique_documents = {unique_documents}",
        "```",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def add_streaming_test_files(path: Path, entries: list[tuple[str, str]]) -> None:
    """Append streaming-test files (huge_log_*, produced by make_huge_file.py
    after this manifest was written) to the coverage table and correct the
    balance numbers accordingly. ``entries``: list of (path, tags)."""
    text = path.read_text(encoding="utf-8")

    table_lines = "\n".join(f"| {p} | contract | txt | {tags} |" for p, tags in entries)
    marker = "## Report balance"
    idx = text.index(marker)
    # Strip the blank line(s) that already separate the table from the
    # marker, so the new rows extend the SAME markdown table instead of
    # starting an orphaned one after a blank line.
    before = text[:idx].rstrip("\n")
    after = text[idx:]
    text = before + "\n" + table_lines + "\n\n" + after

    def bump(field: str, delta: int, s: str) -> str:
        pattern = re.compile(rf"({re.escape(field)}\s*=\s*)(\d+)")
        return pattern.sub(lambda m: m.group(1) + str(int(m.group(2)) + delta), s)

    n = len(entries)
    text = bump("input_files", n, text)
    text = bump("unique_documents", n, text)
    text = text.rstrip("\n") + "\n\n"
    text += (
        f"Note: the {n} streaming-test file(s) above (`huge_log_*`, "
        "DATA_SPEC.md §6) are git-ignored and recreated by "
        "`scripts/make_huge_file.py`, run after `generate_data.py`. The "
        "balance numbers include them because they are physically present "
        "in `data/corpus/` for any `run`/`report` invocation.\n"
    )
    path.write_text(text, encoding="utf-8")
